"""Changes backref names for comments relationship with pitch

Revision ID: 0415462e97de
Revises: fd84a42f330b
Create Date: 2020-05-03 20:54:46.822054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0415462e97de'
down_revision = 'fd84a42f330b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitch_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('comments', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitch_fkey', 'comments', 'pitches', ['pitch'], ['id'])
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
