"""Changes schema User and Pitches to debug

Revision ID: 3e4bfc3c8bce
Revises: 0415462e97de
Create Date: 2020-05-03 21:56:31.491606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4bfc3c8bce'
down_revision = '0415462e97de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'pitch_id')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'content')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('title', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
