"""Updates schema

Revision ID: 46e272ec72a6
Revises: accb0f4a8221
Create Date: 2020-05-04 16:29:00.790255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e272ec72a6'
down_revision = 'accb0f4a8221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_id')
    op.add_column('pitches', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pass_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_code')
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'dislikes')
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###
