"""Adds Comment model

Revision ID: 73cbbf58855e
Revises: d63c70fa8917
Create Date: 2020-05-03 20:15:40.275477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cbbf58855e'
down_revision = 'd63c70fa8917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('content', sa.String(length=1000), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=225), nullable=True))
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'pitch_category')
    op.drop_column('pitches', 'pitch_title')
    op.add_column('users', sa.Column('bio', sa.String(length=5000), nullable=True))
    op.add_column('users', sa.Column('pass_code', sa.String(length=225), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'pass_code')
    op.drop_column('users', 'bio')
    op.add_column('pitches', sa.Column('pitch_title', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_category', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'content')
    op.drop_column('pitches', 'category')
    op.drop_table('comments')
    # ### end Alembic commands ###
