"""Updating comments and pitch

Revision ID: de0b7b86b7b3
Revises: d3fb3befea5d
Create Date: 2020-05-07 13:07:02.729789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0b7b86b7b3'
down_revision = 'd3fb3befea5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'dislikes')
    op.drop_column('pitches', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
