"""Changes user model schema. Adds bio and profile_pic

Revision ID: ed3c48d01235
Revises: 0937c4946292
Create Date: 2020-05-04 11:28:04.471213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3c48d01235'
down_revision = '0937c4946292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=225), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'bio')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'content')
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    # ### end Alembic commands ###
